
spring.application.name=backend

server.port=${PORT:8080}



spring.datasource.url=jdbc:mysql://localhost:3306/predictive_db
spring.datasource.username=root
spring.datasource.password=Shesh@2509

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true